title: Open Source Guide
description: A guide for open source program offices
baseurl: "/oss-guide" # the subpath of your site, e.g. /blog
url: "https://verizonmedia.github.io" # the base hostname & protocol for your site, e.g. http://example.com
remote_theme: pmarsceill/just-the-docs

# Enable or disable the site search
search_enabled: true

# Footer content appears at the bottom of every page's main content
footer_content: "Copyright 2019, Verizon Media, Content licensed under CC-BY-4.0"
